name: Test

on:
  pull_request:
    branches:
    - refactor

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 Tools/sqf_validator.py
    - name: Validate Config
      run: python3 Tools/config_style_checker.py
    - uses: arma-actions/bom-check@v1
      name: Check for BOM

  lint:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      with:
          args: --exit w --directory $GITHUB_WORKSPACE
      continue-on-error: true

  build:
    runs-on: windows-latest
    needs: [validate, lint]
    steps:
      - uses: actions/checkout@v2
      - name: Copy mission files to templates
        run: |
          $mainFolder = "$($Env:GITHUB_WORKSPACE)"
          $templateFolder = "$($Env:GITHUB_WORKSPACE)\Mission-Templates"
          $unwantedFoldersAndFiles = @("mission.sqm", ".vscode", ".github", ".git", ".gitignore", "Mission-Templates", "Pbo-Tools", "Tools")
          $mainFiles = Get-ChildItem -Path "$mainFolder" | Where-Object { $_.Name -notin $unwantedFoldersAndFiles }
          $missionFolders = Get-ChildItem -Path "$templateFolder" -Directory
          if ($missionFolders.Count -gt 0)
          {
              ForEach ($folder in $missionFolders)
              {
                  Write-Output "-----------------------------------------------------"
                  Write-Output "Mission Folder: $folder"
                  Write-Output "-----------------------------------------------------"
                  ForEach ($file in $mainFiles)
                  {
                      Try
                      {
                          Copy-Item -Path "$($file.Fullname)" -Destination "$folder\$($file.Name)" -Recurse -Force
                          Write-Output "    $($file.Name) --> $folder\$($file.Name)"
                      }
                      Catch
                      {
                          $ErrorMessage = $_ | Out-String
                          Write-Output "The following error occured while copying files for $($file.Name) from Main Mission to Template Mission:"
                          Write-Output $ErrorMessage
                      }
                  }
                  Write-Output "-----------------------------------------------------"
              }
          }
        shell: pwsh

      - name: Install Mikero Tools
        run: |
          $PboTools = "$($Env:GITHUB_WORKSPACE)\Pbo-Tools\"
          Get-ChildItem "$PboTools" | ForEach-Object {
            echo "Installing $_"
            Start-Process -Wait $_.FullName "/S"
          }
          echo "Updating environment variables"
          echo "C:\Program Files (x86)\Mikero\DePboTools\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Pack mission files to PBOs
        run: |
          Get-Command makepbo
          $templateFolder = "$($Env:GITHUB_WORKSPACE)\Mission-Templates"
          $missionFolders = Get-ChildItem -Path "$templateFolder" -Directory
          New-Item -Path "$($Env:GITHUB_WORKSPACE)\Publish\" -ItemType Directory
          if ($missionFolders.Count -gt 0)
          {
              ForEach ($folder in $missionFolders)
              {
                  Try
                  {
                    makepbo -P -A -$ -B -X=".bak,.txt" "$folder"
                    Copy-Item -Path "$folder.pbo" -Destination "$($Env:GITHUB_WORKSPACE)\Publish\$($folder.Name).pbo"
                  }
                  Catch
                  {
                      $ErrorMessage = $_ | Out-String
                      Write-Output "The following error occured while packing $($folder.Name):"
                      Write-Output $ErrorMessage
                  }
              }
          }
        shell: pwsh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TRGM-Redux-Missions
          path: ${{ github.workspace }}/Publish/**/*
          if-no-files-found: error